author=Alexander Popoff
group=io.github.aerialist7
version=1.0.0
kotlin.version=2.3.0
kotlin.wrappers.version=2025.12.7
kotlin.code.style=official
kotlin.js.yarn=false
kotlin.js.stdlib.dom.api.included=false
#org.gradle.jvmargs=-Xmx4g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
#https://github.com/JetBrains/kotlin-wrappers/issues/1909
#kotlin.daemon.jvmargs=-Xmx4g
org.gradle.jvmargs=-Xms2g -Xmx4g
